export type Bank = {
  name: string
  short: string
  category: 'Local' | 'Islamic' | 'Foreign' | 'Digital'
  color: string
  logo?: string
  logoBackground?: string
  cardImage?: string
  themeColor?: string
  popular?: boolean
}

// Educational dataset of banks licensed to operate in the UAE.
// Banks without a stored logo fall back to a branded monogram tile.
export const banks: Bank[] = [
  {
    name: 'HSBC Bank Middle East Limited',
    short: 'HS',
    category: 'Foreign',
    color: '#db0011',
    logo: '/logos/hsbc-middle-east.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-bndyirdpKoOtBuJ4khVFmM5XwcTPWH.png',
    themeColor: '#db0011',
  },
  {
    name: 'Standard Chartered Bank',
    short: 'SC',
    category: 'Foreign',
    color: '#0875d1',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Ms1Aa7WoNUaXWtxYVrJgUQq7WpbieD.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-ltQxuX6wg7H76xoPWZ1wTNleXwWbTK.png',
    themeColor: '#061d3a',
  },
  {
    name: 'Emirates NBD Bank P.J.S.C',
    short: 'ENBD',
    category: 'Local',
    color: '#072447',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-EfKiGa1gDijAZw2R5aplII23Thrsys.png',
    logoBackground: '#072447',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9x9QDEFcURY1WTSu5r69IAmFdQCnvj.png',
    themeColor: '#25282b',
  },
  {
    name: 'CitiBank N.A.',
    short: 'CITI',
    category: 'Foreign',
    color: '#005baa',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IpGXkylcqTgDKBXcGWdhdvuQnrShhg.png',
    logoBackground: '#eef0f7',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-g8AOP3Q77L6A1tyPfKZATPeXcEYCOA.png',
    themeColor: '#0066b3',
  },
  {
    name: 'Mashreq Bank P.S.C.',
    short: 'MQ',
    category: 'Local',
    color: '#ed3d1e',
    logo: '/logos/mashreq.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-W2yRQ4u9nCZbL2VMFDdA7onULy5Gp7.png',
    themeColor: '#062d72',
  },
  {
    name: 'Habib Bank Ltd.',
    short: 'HBL',
    category: 'Foreign',
    color: '#008c75',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-16%20104202-5EUnGZyz5XekdHvR4msMWSJZh80jP9.png',
    logoBackground: '#008c75',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-446ND0WA9hdHKJXlpn7ZVJi2snbSp2.png',
    themeColor: '#6f7478',
  },
  {
    name: 'United Bank Ltd.',
    short: 'UBL',
    category: 'Foreign',
    color: '#087eae',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-16%20104242-nGtkomUtjxZID6jGh9XU956tNQy62Z.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-05-01%20105044-n3GeurzuamPNn65RoL2OL9JR2tQOi1.png',
    themeColor: '#073b86',
  },
  {
    name: 'First Abu Dhabi Bank P.J.S.C',
    short: 'FA',
    category: 'Local',
    color: '#0f4c8c',
    logo: '/logos/first-abu-dhabi-bank.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-2iZs2jSJQ4t4b6OKzMPf3JDgqLN96P.png',
    themeColor: '#071d45',
  },
  {
    name: 'Bank Saderat Iran',
    short: 'BSI',
    category: 'Foreign',
    color: '#2d1a70',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-16%20104323-G9XTGs1LyQF3E0czQSJh8hyK9SFQaD.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'Commercial Bank of Dubai P.J.S.C',
    short: 'CD',
    category: 'Local',
    color: '#dd4623',
    logo: '/logos/commercial-bank-of-dubai.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-TMbVVHsQXpIWlS1NCYaLt0ARTm2MKq.png',
    themeColor: '#4a0b0b',
  },
  {
    name: 'Al Ahli Bank of Kuwait',
    short: 'ABK',
    category: 'Foreign',
    color: '#1557d6',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-16%20104358-5V4ulYwFFNt6QRHO32KZ7Hf8J3m079.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-ISR8CYdq687KUjsn2ALSHnMycRjtgN.png',
    themeColor: '#061b4f',
  },
  {
    name: 'Bank Melli Iran',
    short: 'BMI',
    category: 'Foreign',
    color: '#d9232e',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-uZYpPKQbLEErIARV1H7jL2dfh3G1V6.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9w8UzEHaemZPwrvy96Gz0vD1tXSL1a.png',
    themeColor: '#123f82',
  },
  {
    name: 'Arab African International Bank',
    short: 'AAIB',
    category: 'Foreign',
    color: '#1557d6',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-NxTehCyVdLJmU1MuwPGrrKnUOiDdXF.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-e4jP0Ff1ymp3LMxA31KkGWSK7iLKcR.png',
    themeColor: '#202326',
  },
  {
    name: 'Banque Misr',
    short: 'BM',
    category: 'Foreign',
    color: '#c9a227',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-jLlY3IU8g2xUAj8g2Ve1LYHRxwYjlV.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-noopEeA9x7K6YaCaIIrRg6qPbcj2R9.png',
    themeColor: '#a87516',
  },
  {
    name: 'Bank of Sharjah P.J.S.C',
    short: 'BOS',
    category: 'Local',
    color: '#0f4c8c',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-y2C4ur0Xc7wyiNyx16CFb2FjKiPIWF.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-192ZpTHdEAi3utAvwtplh63H1zEDxu.png',
    themeColor: '#8a5a2b',
  },
  {
    name: 'BNP Paribas',
    short: 'BNP',
    category: 'Foreign',
    color: '#008c61',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-lV435LfUU5quG5TzxXHhrYeLxDXJoO.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-GzUAl289EL07fE98zgv8YImzo3rPPA.png',
    themeColor: '#006b4f',
  },
  {
    name: 'Al Khaliji (France) S. A.',
    short: 'AKF',
    category: 'Foreign',
    color: '#f28c18',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-brgoGhJFfxDFHtNr21Pj6XGPvXuj51.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'Rafidain Bank',
    short: 'RB',
    category: 'Foreign',
    color: '#187a45',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-i33eqcHZcmhdo8H1GifZjPowXwsDwU.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-sknemuQQWhkXhKPSaqNq93dI8cj8FN.png',
    themeColor: '#1b1d20',
  },
  {
    name: 'Bank of Baroda',
    short: 'BB',
    category: 'Foreign',
    color: '#f47321',
    logo: '/logos/bank-of-baroda.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Wo2FkQUVR8V1D27OvYTlXeGdB1gQ63.png',
    themeColor: '#e34b16',
  },
  {
    name: 'Janata Bank PLC',
    short: 'JB',
    category: 'Foreign',
    color: '#12b5d0',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-F8V28pgRm6H0MLvc4YpQJ5sR7NcYZG.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-ofN7Sb386QbaQp2Z6BiNAycxosKe6l.png',
    themeColor: '#0877d1',
  },
  {
    name: 'Habib Bank A.G Zurich',
    short: 'HB',
    category: 'Foreign',
    color: '#0f6b3c',
    logo: '/logos/habib-bank-ag-zurich.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-J5hyAlsMaGU4cZ8hOuwbikC3dAd9QI.png',
    themeColor: '#697276',
  },
  {
    name: 'Banque Banorient France',
    short: 'BF',
    category: 'Foreign',
    color: '#075493',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-CNNgNCW8QbJzEHZggak6M67nMn3H6U.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-tve7WH3otx39CAQRm5jaEnhPfp7mx1.png',
    themeColor: '#061f75',
  },
  {
    name: 'Dubai Islamic Bank (DIB)',
    short: 'DI',
    category: 'Islamic',
    color: '#0e7a4a',
    logo: '/logos/dubai-islamic-bank.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-W4aCNqSl1uCu6aMjTjICmERYpA9xpI.png',
    themeColor: '#a7adb3',
  },
  {
    name: 'Sharjah Islamic Bank P.J.S.C.',
    short: 'SIB',
    category: 'Islamic',
    color: '#152b74',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-c6LzEN2UaGClLQJa8vNzpV20HuSP5q.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-t3qWXIARYnuK9LGsJ80fI1gb3uuccL.png',
    themeColor: '#aeb4bc',
  },
  {
    name: 'United Arab Bank P.J.S.C',
    short: 'UA',
    category: 'Local',
    color: '#0f4c8c',
    logo: '/logos/united-arab-bank.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-DHAg9Wz6GcpYWrB09EpeZRVtQoMGOj.png',
    themeColor: '#073b86',
  },
  {
    name: 'InvestBank P.J.S.C',
    short: 'IB',
    category: 'Local',
    color: '#ad914c',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-uZK7DVc75pPp5Y0FR3Meru6cKqCTmb.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-yuE9uPTVd8zn8uipu6dAvkV8M4TejL.png',
    themeColor: '#4e5358',
  },
  {
    name: 'Credit Agricole- Corporate and Investment Bank',
    short: 'CA',
    category: 'Foreign',
    color: '#007a53',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-D58AulZGWwpVhjkYMXf4OtKgiMzT2P.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'Arab Bank for Inv.& Foreign Trade',
    short: 'AF',
    category: 'Foreign',
    color: '#122b67',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-slWugBPfzqph7WaqUU3hSoTfY0cto0.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-huG4ZRgsxos8PUs8MGLt8IVVaaRvrZ.png',
    themeColor: '#4e5358',
  },
  {
    name: 'Emirates Islamic Bank P.J.S.C.',
    short: 'EI',
    category: 'Islamic',
    color: '#492056',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-15%20224412-d1aF6TYIe6N6ZmxALz7BwCuEXTeKQH.png',
    logoBackground: '#492056',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-s2r3249GLKcPs2IuP2tt2bxGOeSMEg.png',
    themeColor: '#24272b',
  },
  {
    name: 'National Bank of R.A.K P.J.S.C',
    short: 'RAK',
    category: 'Local',
    color: '#e30613',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-b7FvaO5dW7BpjpWOKQR2Q83Q2os2A9.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-pZpx0A3QhM6rGjtuaZj9ciGFDkDuXA.png',
    themeColor: '#4a2813',
  },
  {
    name: 'El Nilein Bank',
    short: 'EN',
    category: 'Foreign',
    color: '#28237a',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Y1zCHnLFWV7OscVbtJ2FmlAwyGqe7i.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'National Bank of Oman S.A.O.G.',
    short: 'NBO',
    category: 'Local',
    color: '#005baa',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-pe3jtKQP6bHTkdnnIOs9Rh22vfXSsf.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-zMef2uNQceJDPGgF0DCEUZj0BkvUn0.png',
    themeColor: '#b8bdc3',
  },
  {
    name: 'National Bank of U.A.Q PSC',
    short: 'NBOQ',
    category: 'Local',
    color: '#0068a9',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-qAKow8DIhbVsGfPwBbbNi62os1MKg7.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Q3VNkXmLADgg2KnTKlGc1Qa5icwlGK.png',
    themeColor: '#a97816',
  },
  {
    name: 'National Bank of Bahrain',
    short: 'NA',
    category: 'Local',
    color: '#0f4c8c',
    logo: '/logos/national-bank-of-bahrain.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-aOxtTt2ZYSZSaroWCXaarzVAcmgnGc.png',
    themeColor: '#0b2238',
  },
  {
    name: 'National Bank of Fujairah PSC',
    short: 'NF',
    category: 'Local',
    color: '#0f4c8c',
    logo: '/logos/nbf.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-szQlzAf40XnJc55LzDYaUlAU08RtjU.png',
    themeColor: '#0b2c58',
  },
  {
    name: 'Abu Dhabi Commercial Bank P.J.S.C',
    short: 'ADCB',
    category: 'Local',
    color: '#bc2026',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-MSpReG6kEm14hNeBDNwFuXJyYjzXQL.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-yDzInnywVX59tY4kdTWPISGeXqhA0a.png',
    themeColor: '#b5161b',
  },
  {
    name: 'Commercial Bank International P.J.S.C',
    short: 'CBI',
    category: 'Foreign',
    color: '#092669',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-dxFHwOKjgr7LI1PkaM0b9lImQvbAjR.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-UoHd3RbvnHheXVn7VE7HRGgJ5FukEJ.png',
    themeColor: '#0a1838',
  },
  {
    name: 'Abu Dhabi Islamic Bank P.J.S.C',
    short: 'ADIB',
    category: 'Islamic',
    color: '#005baa',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-8NczZvvl9bhBInbddR5QqIPLBarGYN.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Ai4rNYzXjqUxyNFwE6tU8gwYRdlbaM.png',
    themeColor: '#063c52',
  },
  {
    name: 'Al Hilal Bank P.J.S.C',
    short: 'AHB',
    category: 'Foreign',
    color: '#291443',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Qgrzl9b3Ukd3BOnB9TSc99bLpUSioY.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-J6qwiumOzUovGaytZ9EkdGoFffAxTN.png',
    themeColor: '#17191d',
  },
  {
    name: 'Doha Bank',
    short: 'DB',
    category: 'Foreign',
    color: '#1b3a6b',
    logo: '/logos/doha-bank.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HqPC64HB5qkcUc51A9OHV2W3WX9tZH.png',
    themeColor: '#6d123f',
  },
  {
    name: 'The Saudi National Bank',
    short: 'SNB',
    category: 'Foreign',
    color: '#006b57',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Fbn7HyBUqRsdFrKLqAmOIxsvs4qASv.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Z83KmU7pZrlIbKcc1FxcjtHmbej8Ts.png',
    themeColor: '#0a4b3b',
  },
  {
    name: 'Ajman Bank P.J.S.C',
    short: 'AJB',
    category: 'Local',
    color: '#e8751a',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Pu9PFab81obk3r1qK4VZh4Xx653RiB.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mBUqrs4gJALPTfCvXwJyVUaTyiYX7C.png',
    themeColor: '#1f1d1b',
  },
  {
    name: 'National Bank of Kuwait',
    short: 'NBK',
    category: 'Local',
    color: '#004b93',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-16%20103308-S5cDFUJhvdxQNVmeJ8wyDLssUrvl1o.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IyqS6smuOEO8VniuhR9HOlKY8TTm5b.png',
    themeColor: '#174b87',
  },
  {
    name: 'Industrial & Commercial Bank of China',
    short: 'ICBC',
    category: 'Foreign',
    color: '#c8102e',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-rTQkSKJGOfvp6rwMTfbCp0dvCNulyf.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Fe3dlXOsLn4d6IQ21UVznfzwrQ5Oec.png',
    themeColor: '#0b2d58',
  },
  {
    name: 'Deutsche Bank AG',
    short: 'DB',
    category: 'Foreign',
    color: '#003399',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-pg2u9ho4L8BDzcPSUQpQWr3UyuDQIz.png',
    logoBackground: '#ffffff',
    cardImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-kP9oYZOJ9vKB1R8HRc7vvj9oVr5ixd.png',
    themeColor: '#8a5b17',
  },
  {
    name: 'KEB Hana Bank',
    short: 'KH',
    category: 'Foreign',
    color: '#009b93',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-DQXhmZS9DZaCLEs2gvfjyjl9P93Qws.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'Barclays Bank PLC',
    short: 'BARC',
    category: 'Foreign',
    color: '#169bd5',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-3MxzTNLgczGInR1WuoEDyhCyFwzgYv.png',
    logoBackground: '#ffffff',
  },
  { name: 'Bank of China Limited', short: 'BC', category: 'Foreign', color: '#a71930', logo: '/logos/bank-of-china.png', logoBackground: '#ffffff' },
  {
    name: 'Gulf International Bank B.S.C',
    short: 'GIB',
    category: 'Foreign',
    color: '#173bba',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-cZHzA0LSvaPJhnl8cjAbDpq4k55pWY.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'MCB Bank Limited',
    short: 'MCB',
    category: 'Foreign',
    color: '#00843d',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-NdZiX9fz62aGETdDezoVQyuqzoytDm.png',
    logoBackground: '#ffffff',
  },
  { name: 'Intesa Sanpaolo S.P.A', short: 'IS', category: 'Foreign', color: '#1b3a6b', logo: '/logos/intesa-sanpaolo.png', logoBackground: '#ffffff' },
  {
    name: 'Agricultural Bank of China Ltd.',
    short: 'ABC',
    category: 'Foreign',
    color: '#12856f',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-4OQCj2ANoaxY4F8QBIcMcWcrAkCms3.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'Bank Al Falah Limited',
    short: 'BAF',
    category: 'Foreign',
    color: '#d21f12',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-W1XF4hm9rGD8YAgrnVC3yEKWwjooFh.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'BOK International Bank',
    short: 'BOK',
    category: 'Foreign',
    color: '#008b68',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-JUsmB4jxCVpQqNM3SWp9jXbbWnhmW0.png',
    logoBackground: '#ffffff',
  },
  { name: 'Al Maryah Community Bank L.L.C.', short: 'AM', category: 'Local', color: '#0f4c8c', logo: '/logos/al-maryah-community-bank.png', logoBackground: '#ffffff' },
  {
    name: 'WIO Bank P.J.S.C',
    short: 'WIO',
    category: 'Digital',
    color: '#4a16df',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-15%20224710-XOxRblCpr6ToWGlPZtpMBJ19b7RJoY.png',
    logoBackground: '#f1f0ed',
  },
  {
    name: 'Zand Bank P.J.S.C',
    short: 'ZAND',
    category: 'Digital',
    color: '#9a5a3a',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-15%20224748-JvpQHRUWYi0mfVa0pZxwz7iKT5lz6h.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'International Development Bank for Investment & Finance',
    short: 'IDB',
    category: 'Foreign',
    color: '#d71920',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-7lV188MJ9kbGHN41qyewf1byT6iz1c.png',
    logoBackground: '#ffffff',
  },
  {
    name: 'Ruya Community Islamic Bank L.L.C',
    short: 'RUYA',
    category: 'Islamic',
    color: '#0c6070',
    logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-MNvQ7WjKNcljN4Qr2kboCa4rRi7unG.png',
    logoBackground: '#ffffff',
  },
]

export const popularBanks = banks.filter((b) => b.popular)

// Convert a bank name into a URL-safe slug, e.g. "ADCB" -> "adcb".
export function bankSlug(name: string) {
  return name
    .toLowerCase()
    .replace(/[()]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export function getBankBySlug(slug: string) {
  return banks.find((b) => bankSlug(b.name) === slug)
}

export type Category = Bank['category']

export const categories: Category[] = ['Local', 'Islamic', 'Foreign', 'Digital']

// Tailwind utility classes per category for consistent color-coded badges.
export const categoryStyles: Record<Category, string> = {
  Local: 'bg-primary/10 text-primary ring-1 ring-inset ring-primary/20',
  Islamic:
    'bg-emerald-500/10 text-emerald-600 ring-1 ring-inset ring-emerald-500/20 dark:text-emerald-400',
  Foreign:
    'bg-purple-500/10 text-purple-600 ring-1 ring-inset ring-purple-500/20 dark:text-purple-400',
  Digital:
    'bg-accent/20 text-accent-foreground ring-1 ring-inset ring-accent/30 dark:text-accent',
}

export function countByCategory(category: Category) {
  return banks.filter((b) => b.category === category).length
}
